services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./backup:/backup

  user:
    build: ./user
    container_name: user
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3001

  spot:
    build: ./spot
    container_name: spot
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3002

  reservation:
    build: ./reservation
    container_name: reservation
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3003

  facade:
    build: ./facade
    container_name: facade
    ports:
        - target: 3004
          published: 3004
          protocol: tcp
          mode: host
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3004
      - USER_URL=http://user:3001
      - SPOT_URL=http://spot:3002
      - RESERVATION_URL=http://reservation:3003